export function createRestartBootstrapScript({
  parentPid,
  cwd
}: {
  parentPid: number;
  cwd: string;
}): string {
  return [
    "const { spawn } = require('node:child_process');",
    "const fs = require('node:fs');",
    "const path = require('node:path');",
    `const repoCwd = ${JSON.stringify(cwd)};`,
    `const parentPid = ${JSON.stringify(parentPid)};`,
    "const runtimeDir = path.join(repoCwd, '.runtime');",
    "const logPath = path.join(runtimeDir, 'restart-bootstrap.log');",
    "const wscriptPath = 'C:\\\\Windows\\\\System32\\\\wscript.exe';",
    "const restartScriptPath = path.join(repoCwd, 'scripts', 'restart-dex-agent-hidden.vbs');",
    "const maxWaitMs = 15000;",
    "const pollIntervalMs = 250;",
    "const settleDelayMs = 1500;",
    "",
    "function logLine(message) {",
    "  try {",
    "    fs.mkdirSync(runtimeDir, { recursive: true });",
    "    fs.appendFileSync(logPath, `[${new Date().toISOString()}] ${message}\\n`, 'utf8');",
    "  } catch {}",
    "}",
    "",
    "function isProcessAlive(pid) {",
    "  try {",
    "    process.kill(pid, 0);",
    "    return true;",
    "  } catch (error) {",
    "    return Boolean(error && error.code !== 'ESRCH');",
    "  }",
    "}",
    "",
    "async function main() {",
    "  const startedAt = Date.now();",
    "  while (isProcessAlive(parentPid) && Date.now() - startedAt < maxWaitMs) {",
    "    await new Promise((resolve) => setTimeout(resolve, pollIntervalMs));",
    "  }",
    "",
    "  await new Promise((resolve) => setTimeout(resolve, settleDelayMs));",
    "",
    "  const child = spawn(wscriptPath, [restartScriptPath], {",
    "    cwd: repoCwd,",
    "    env: process.env,",
    "    detached: true,",
    "    windowsHide: true,",
    "    stdio: 'ignore'",
    "  });",
    "  child.unref();",
    "  logLine(`spawned restart via ${restartScriptPath}`);",
    "}",
    "",
    "main().catch((error) => {",
    "  const detail = error && error.stack ? error.stack : String(error);",
    "  logLine(`restart bootstrap failed: ${detail}`);",
    "  process.exit(1);",
    "});"
  ].join("\n");
}
